// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCASTCOih808kLfPlpQ9-gRb82hniRc_4k',
//     appId: '1:471866643979:web:8ce08a001d585ea173590e',
//     messagingSenderId: '471866643979',
//     projectId: 'namastethailand-22dbf',
//     authDomain: 'namastethailand-22dbf.firebaseapp.com',
//     storageBucket: 'namastethailand-22dbf.appspot.com',
//     measurementId: 'G-GLWCDG6MKH',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC6eSK1SsFJMVZHEjDvrodXip6dRH-psHw',
//     appId: '1:889481453393:ios:cae3a10ac5e93beb87bd70',
//     messagingSenderId: '471866643979',
//     projectId: 'self-learning-d2ecd',
//     storageBucket: 'self-learning-d2ecd.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBTZPlzVFZcrVLC3al5SioaWjCiagyCknY',
//     appId: '1:889481453393:ios:cae3a10ac5e93beb87bd70',
//     messagingSenderId: '471866643979',
//     projectId: 'self-learning-d2ecd',
//     storageBucket: 'namastethailand-22dbf.appspot.com',
//     iosBundleId: 'com.self.learn',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC2S1uvD1CdArqQ-D4S2BP9wNz-hH2rpdE',
//     appId: '1:471866643979:ios:b9b2c2c471e3a77e73590e',
//     messagingSenderId: '471866643979',
//     projectId: 'namastethailand-22dbf',
//     storageBucket: 'namastethailand-22dbf.appspot.com',
//     iosClientId: '471866643979-v70lgcat0g264le36apfspthnvdnmid7.apps.googleusercontent.com',
//     iosBundleId: 'com.pearlorganisation.namasteThailand',
//   );
// }